#!/usr/bin/env python3
"""Generate wpml-config.xml from section field maps and manifest data.

Reads config/section-field-maps.json and manifests/pages/*.json to produce
a complete WPML config with per-field and per-sub-key entries.

Usage:
  python scripts/generate-wpml-config.py           # write wpml-config.xml
  python scripts/generate-wpml-config.py --dry-run  # print to stdout
  python scripts/generate-wpml-config.py --check    # exit 1 if out of date
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
FIELD_MAPS_PATH = PROJECT_ROOT / "config" / "section-field-maps.json"
MANIFESTS_DIR = PROJECT_ROOT / "manifests" / "pages"
OUTPUT_PATH = PROJECT_ROOT / "wpml-config.xml"

COPY_SUB_KEYS = frozenset({
    "href", "url", "link", "icon", "variant", "index",
    "image_url", "media_image_url", "photo_url", "image_position", "tag",
})

COPY_ONCE_SUB_KEYS = frozenset({"href", "url", "link"})


def load_field_maps() -> dict[str, list[dict[str, Any]]]:
    data = json.loads(FIELD_MAPS_PATH.read_text(encoding="utf-8"))
    return data.get("pages", {})


def load_manifest(slug: str) -> dict[str, Any] | None:
    path = MANIFESTS_DIR / f"{slug}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def discover_sub_keys(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    keys: dict[str, None] = {}
    for item in value:
        if isinstance(item, dict):
            for k in item:
                if not k.startswith("_"):
                    keys[k] = None
    return list(keys.keys())


def sub_key_action(key: str) -> str:
    if key in COPY_ONCE_SUB_KEYS:
        return "copy-once"
    if key in COPY_SUB_KEYS:
        return "copy"
    return "translate"


def generate_xml(field_maps: dict[str, list[dict[str, Any]]]) -> str:
    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!--",
        "  WPML Translation Configuration.",
        "  AUTO-GENERATED by scripts/generate-wpml-config.py",
        "  DO NOT EDIT MANUALLY.",
        "-->",
        "<wpml-config>",
        "",
        "  <custom-fields>",
        "    <!-- Base fields (structural) -->",
        '    <custom-field action="copy">starter_page_family</custom-field>',
        '    <custom-field action="copy">starter_page_sections</custom-field>',
    ]

    for page_slug, sections in sorted(field_maps.items()):
        manifest = load_manifest(page_slug)
        manifest_sections = manifest.get("sections", []) if manifest else []

        lines.append("")
        lines.append(f"    <!-- {'=' * 50} -->")
        lines.append(f"    <!-- {page_slug.upper()} PAGE -->")
        lines.append(f"    <!-- {'=' * 50} -->")

        for si, sdef in enumerate(sections):
            lines.append("")
            lines.append(f"    <!-- {sdef['type']} (#{si + 1}) -->")

            ms = manifest_sections[si] if si < len(manifest_sections) else {}

            for fname, fdef in sdef.get("fields", {}).items():
                mk = f"{sdef['prefix']}_{fname}"
                wpml = fdef.get("wpml", "translate") if isinstance(fdef, dict) else "translate"
                storage = fdef.get("storage", "text") if isinstance(fdef, dict) else str(fdef)

                lines.append(f'    <custom-field action="{wpml}">{mk}</custom-field>')

                if storage == "json" and wpml == "translate":
                    for sk in discover_sub_keys(ms.get(fname)):
                        lines.append(
                            f'    <custom-field action="{sub_key_action(sk)}">'
                            f"{mk}|{sk}|*|0|value</custom-field>"
                        )

    lines += ["", "  </custom-fields>", "", "</wpml-config>", ""]
    return "\n".join(lines)


def main() -> None:
    os.chdir(PROJECT_ROOT)
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    field_maps = load_field_maps()

    xml = generate_xml(field_maps)

    if args.check:
        if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text(encoding="utf-8").strip() == xml.strip():
            print("wpml-config.xml is up to date")
            sys.exit(0)
        print("wpml-config.xml is OUT OF DATE")
        sys.exit(1)

    if args.dry_run:
        print(xml)
        return

    OUTPUT_PATH.write_text(xml, encoding="utf-8")
    total = xml.count("<custom-field")
    print(f"wrote wpml-config.xml — {total} entries")


if __name__ == "__main__":
    main()
