#!/usr/bin/env bash
# Install and harden a local WordPress instance with WP-CLI.
# Requires .env generated by scripts/generate-env.mjs.

set -euo pipefail

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found. Run: pnpm env:generate -- --slug <site> --port <port> --db-port <db-port>" >&2
  exit 1
fi

set -a
source ./.env
set +a

SITE_URL="${WP_SITE_URL:-http://127.0.0.1:${PORT:-8000}}"
SITE_TITLE="${WP_SITE_TITLE:-${THEME_SLUG:-Starter Site}}"

required=(WP_ADMIN_USER WP_ADMIN_PASSWORD WP_ADMIN_EMAIL THEME_SLUG)
for key in "${required[@]}"; do
  if [[ -z "${!key:-}" ]]; then
    echo "ERROR: $key is required in .env" >&2
    exit 1
  fi
done

wp() {
  docker compose --profile cli run --rm wpcli wp "$@"
}

if ! wp core is-installed >/dev/null 2>&1; then
  wp core install \
    --url="$SITE_URL" \
    --title="$SITE_TITLE" \
    --admin_user="$WP_ADMIN_USER" \
    --admin_password="$WP_ADMIN_PASSWORD" \
    --admin_email="$WP_ADMIN_EMAIL" \
    --skip-email
else
  echo "WordPress already installed; skipping core install."
fi

wp theme activate "$THEME_SLUG"
wp option update users_can_register 0
wp option update default_role subscriber
wp rewrite structure '/%postname%/' --hard
wp cache flush || true

if wp user get admin >/dev/null 2>&1; then
  new_id="$(wp user get "$WP_ADMIN_USER" --field=ID)"
  old_id="$(wp user get admin --field=ID)"
  wp user delete "$old_id" --reassign="$new_id" --yes
fi

echo "OK: local WordPress install ready at $SITE_URL"
